version: "3.8"
services:
  postgres:
    image: 'postgres'
    restart: always
    volumes: 
      - data:/data/db
    environment:
      POSTGRES_PASSWORD: password
    ports: 
      - '5432:5432'
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
    environment:
      BACKEND_HOSTNAME: "192.168.40.170" #HOSTNAME OF BACKEND
      BACKEND_PORT: "5000" #PORT BACKEND RUNS ON
      TESS_LANGUAGE: "slk"
      PADDLE_LANGUAGE: "en"
    depends_on: 
      - postgres
  frontend: 
    build: ./frontend
    ports: 
      - '3000:3000'
    volumes: 
      - ./frontend/src:/app/src
    environment:
      REACT_APP_BACKEND_HOSTNAME: "192.168.40.170" #HOSTNAME OF BACKEND
      REACT_APP_BACKEND_PORT: "5000" #PORT BACKEND RUNS ON
    stdin_open: true
    tty: true
    depends_on: 
      - backend
volumes: 
  data: